/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Usuario;
import Clases.Validaciones;
import Clases.Conexion;
import Clases.SimpleTimer;
import Popups.Popup;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Properties;
import javax.swing.ImageIcon;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormatter;
import org.joda.time.format.ISODateTimeFormat;

public class Login extends javax.swing.JFrame {
    
    Popup p = new Popup();
    Validaciones val = new Validaciones();
    Usuario usuario = new Usuario();
    Conexion Con = new Conexion();
    SimpleTimer st = new SimpleTimer();
    private static Connection con;
    private int rem = 0;
    private int Intentos = 0;
    
    public Login() {
        super("TortiYA");
        initComponents();
        CheckLock();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("src/Iconos/LogoApp.png").getImage());
        this.setOpacity(0.97f);
    }
    
    private void CheckLock(){
        String LockTime = Con.getLockingDate();
        DateTime ltime = new DateTime(LockTime);
        DateTime now = new DateTime();
        String ltimeStr = ltime.toString();
        String nowStr = now.toString();
        DateTimeFormatter fmt = ISODateTimeFormat.dateTime();
        DateTimeFormatter fmt2 = ISODateTimeFormat.dateTime();
        DateTime newltime = fmt.parseDateTime(ltimeStr);
        DateTime newnow = fmt2.parseDateTime(nowStr);
        int milst = (int) (newnow.getMillis() - newltime.getMillis());
        if(milst > 300000){
            ///
        }
        else{
            txtusu.setEditable(false);
            BotonIngresar.setEnabled(false);
            rem = 300000 - milst;
            Alerta.setText("Demasiados intentos fallidos. Podrá acceder de nuuevo en "+st.ElapsedTimeRemainingMilisString(rem));
            rem -= 1000;
            t.start();
        }
    }
    
    javax.swing.Timer t = new javax.swing.Timer(1000, new ActionListener(){
          public void actionPerformed(ActionEvent e) {
              if(rem / 1000 > 0){
              Alerta.setText("Demasiados intentos fallidos. Podrá acceder de nuuevo en "+st.ElapsedTimeRemainingMilisString(rem));
              rem -= 1000;
              }
              else{
                  Alerta.setText("");
                  BotonIngresar.setEnabled(true);
                  txtusu.setEditable(true);
                  t.stop();
              }
          }
            });
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIzquierda = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        TituloApp = new javax.swing.JLabel();
        BotonConf = new rojeru_san.complementos.RSButtonHover();
        PanelDerecha = new javax.swing.JPanel();
        SeparadorUsu = new javax.swing.JSeparator();
        LabelUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonIngresar = new rojeru_san.complementos.RSButtonHover();
        BotonSalir = new rojeru_san.complementos.RSButtonHover();
        txtusu = new javax.swing.JPasswordField();
        Alerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzquierda.setBackground(new java.awt.Color(255, 199, 125));
        PanelIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/logo4.png"))); // NOI18N
        PanelIzquierda.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -20, -1, 373));

        TituloApp.setBackground(new java.awt.Color(255, 255, 255));
        TituloApp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        TituloApp.setForeground(new java.awt.Color(27, 34, 36));
        TituloApp.setText("TortiYA");
        PanelIzquierda.add(TituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        BotonConf.setBackground(new java.awt.Color(255, 199, 125));
        BotonConf.setBorder(null);
        BotonConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Config45.png"))); // NOI18N
        BotonConf.setColorHover(new java.awt.Color(255, 187, 97));
        BotonConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfActionPerformed(evt);
            }
        });
        PanelIzquierda.add(BotonConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 60));

        getContentPane().add(PanelIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 460));

        PanelDerecha.setBackground(new java.awt.Color(27, 34, 36));
        PanelDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelDerecha.add(SeparadorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 270, 10));

        LabelUsuario.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario");
        PanelDerecha.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Iniciar Sesión");
        PanelDerecha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        BotonIngresar.setBackground(new java.awt.Color(20, 26, 27));
        BotonIngresar.setBorder(null);
        BotonIngresar.setText("Ingresar");
        BotonIngresar.setColorHover(new java.awt.Color(255, 199, 125));
        BotonIngresar.setColorTextHover(new java.awt.Color(0, 0, 0));
        BotonIngresar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 90, 40));

        BotonSalir.setBackground(new java.awt.Color(27, 34, 36));
        BotonSalir.setBorder(null);
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cerrar45.png"))); // NOI18N
        BotonSalir.setColorHover(new java.awt.Color(20, 26, 27));
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelDerecha.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 60));

        txtusu.setBackground(new java.awt.Color(27, 34, 36));
        txtusu.setFont(new java.awt.Font("Andis", 0, 18)); // NOI18N
        txtusu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusu.setBorder(null);
        PanelDerecha.add(txtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 270, 30));

        Alerta.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        Alerta.setForeground(new java.awt.Color(255, 102, 102));
        PanelDerecha.add(Alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 350, 20));

        getContentPane().add(PanelDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 390, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        String Cadena = txtusu.getText();
        if((val.ValidarContenido(Cadena) == false)||(val.ValidarLongitud(Cadena,11) == false) || (val.ValidarNums(Cadena) == false)){
            txtusu.setText("");
            if(Intentos<5){
                p.Error(this, "Caractéres Inválidos");}
            ++Intentos;
        }
        else{
            con = Con.ConectarLogin(this);
            if(Con.ConsultaLogin(con, Cadena) == true){
              usuario = Con.PostConsultaLogin(usuario, con, Cadena);
              this.dispose();
              p.MsgCerrar();
              Menu ME = new Menu(con,usuario);
              ME.setVisible(true);
            }
            else{
                if(Intentos<5){
                    p.Error(this, "Usuario inválido");}
                ++Intentos;
            }
            
        }
        if(Intentos>=5){
            Con.setLockingDate(new DateTime().toString());
            txtusu.setEditable(false);
            BotonIngresar.setEnabled(false);
            rem = 300000;
            Alerta.setText("Demasiados intentos fallidos. Podrá acceder de nuuevo en "+st.ElapsedTimeRemainingMilisString(rem));
            rem -= 1000;
            t.start();
        }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void BotonConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfActionPerformed
        this.dispose();
        Config config = new Config();
        config.setVisible(true);
    }//GEN-LAST:event_BotonConfActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    private rojeru_san.complementos.RSButtonHover BotonConf;
    private rojeru_san.complementos.RSButtonHover BotonIngresar;
    private rojeru_san.complementos.RSButtonHover BotonSalir;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelDerecha;
    private javax.swing.JPanel PanelIzquierda;
    private javax.swing.JSeparator SeparadorUsu;
    private javax.swing.JLabel TituloApp;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtusu;
    // End of variables declaration//GEN-END:variables
}
